### ISSUE TITLE
why obfuscate

### ISSUE THREAD

**Issue by KingKDot** [TheAxes/Discord-Nuke-Bot-V3#2]
ruins the purpose of github

**Comment by TheAxes** [comment]
No One Cares.

**Comment by KingKDot** [comment]
> No One Cares.

But why obfuscate u ain't allat good at coding

**Comment by TheAxes** [comment]
Who asked

**Comment by KingKDot** [comment]
> Who asked

bros saying who asked cause he can't leave his code open source 😭

**Comment by effyxt** [comment]
[source.txt](https://github.com/TheAxes/Discord-Nuke-Bot-V3/files/11078054/source.txt)
@KDot227  if you need the source

**Comment by TheAxes** [comment]
No one need kid.
