### ISSUE TITLE
Dumbo

### ISSUE THREAD

**Issue by haxmcdev** [TheAxes/Discord-Nuke-Bot-V3#4]
post real src

**Comment by TheAxes** [comment]
Kid never.

**Comment by haxmcdev** [comment]
don't close it idiot it's not completed. You're a sucking token grabber

**Comment by TheAxes** [comment]
> don't close it idiot it's not completed. You're a sucking token grabber

Can't Deobfuscate?
And can see it's not a grabber 
Skid.

**Comment by haxmcdev** [comment]
Skid for sure lol it is a grabber

**Comment by TheAxes** [comment]
> Skid for sure lol it is a grabber

Where tell me skid
Lol u can't tell cuz there is no grabber only skids like u put grabber in scripts kid

**Comment by KingKDot** [comment]
> > don't close it idiot it's not completed. You're a sucking token grabber
> 
> Can't Deobfuscate? And can see it's not a grabber Skid.

how u gonna call him a skid when u obfuscate code on github 💀

**Comment by TheAxes** [comment]
He want src to skid it lmfao

**Comment by KingKDot** [comment]
> He want src to skid it lmfao

Bro ain't nobody wanna skid your slow ass nuker

**Comment by KingKDot** [comment]
1 print and your obfuscation ( that you didn't make) is gone

**Comment by TheAxes** [comment]
Who Cares?

**Comment by KingKDot** [comment]
> Who Cares?

the entire github community since it's for "Open source developing"

**Comment by TheAxes** [comment]
> > Who Cares?
> 
> the entire github community since it's for "Open source developing"

Idc

**Comment by KingKDot** [comment]
> > > Who Cares?
> > 
> > 
> > the entire github community since it's for "Open source developing"
> 
> Idc

weirdo
